apiVersion: v1
kind: ServiceAccount
metadata:
  name: hello-operator
  labels:
    app: hello-operator
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hello-operator
  labels:
    app: hello-operator
rules:
- apiGroups: ["apiextensions.k8s.io"] 
  resources: ["customresourcedefinitions"]
  verbs: ["list", "create"]

- apiGroups: ["operators.rahulrai.net"] 
  resources: ["helloapp"]
  verbs: ["list", "watch", "get"]

- apiGroups: [""] 
  resources: ["configmaps"]
  verbs: ["list", "create", "delete"]

- apiGroups: ["apps"] 
  resources: ["deployments"]
  verbs: ["list", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hello-operator
  labels:
    app: hello-operator
subjects:
- kind: ServiceAccount
  name: hello-operator
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: hello-operator